Adding user restrictions
LesliNieto/MarketPlace pull request #24
Opened 2018-12-28 20:43 UTC by LinaGallardo

In this branch, I adding restrictions for delete user.  
![user_restrictions](https://user-images.githubusercontent.com/43416022/50527559-2a828300-0ab7-11e9-8201-3f82b47fe98d.gif)

2018-12-28 21:22 UTC, fonsecajavier requested changes
Code is fine, but I'd also add something in the `users#show` view so that you hide the "Cancel my account" button if `@user != current_user`

2018-12-28 21:25 UTC, LinaGallardo commented
Okay, no problem

2018-12-28 21:54 UTC, LinaGallardo commented
@fonsecajavier The commit it's ready. 
![user_login](https://user-images.githubusercontent.com/43416022/50529189-2c514400-0ac1-11e9-9900-3fa5f390f683.gif)

2019-01-03 16:31 UTC, fonsecajavier approved these changes

2019-01-03 16:36 UTC, merged